### ISSUE TITLE
this._auth.xoauth2 does not have method 'getToken'

### ISSUE THREAD

**Issue by ggallo** [andris9/smtp-connection#25]
Using [nodemailer-smtp-transport](https://github.com/andris9/nodemailer-smtp-transport/tree/v1.0.3)@1.0.3 via [nodemailer](https://github.com/andris9/Nodemailer/tree/v1.5.0)@1.5.0

Setting up the mailer:
```
var transporter = nodemailer.createTransport({
        service: 'gmail',
        auth: {
          xoauth2: {
            user: "XXXXXXXX@gmail.com",
            clientId: "XXXXXXX.apps.googleusercontent.com",
            clientSercret: "XXXXXXXXXX",
            refreshToken: "XXXXXXXX"
          }
        }
    });
```

And the resulting error:
```
TypeError: Object #<Object> has no method 'getToken'
    at SMTPConnection._handleXOauth2Token (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:961:67)
    at SMTPConnection.login (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:233:18)
    at SMTPTransport.<anonymous> (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/src/smtp-transport.js:96:24)
    at SMTPConnection.g (events.js:180:16)
    at SMTPConnection.emit (events.js:92:17)
    at SMTPConnection._actionEHLO (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:692:10)
    at SMTPConnection._processResponse (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:511:16)
    at SMTPConnection._onData (/home/ec2-user/node_modules/nodemailer/node_modules/nodemailer-smtp-transport/node_modules/smtp-connection/src/smtp-connection.js:357:10)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)
    at _stream_readable.js:420:7
    at process._tickCallback (node.js:442:13)
```
The initial offending code for [convenience](https://github.com/andris9/smtp-connection/blob/v1.3.1/src/smtp-connection.js#L955).

**Comment by ggallo** [comment]
Wow I am just embarrassing myself today:
```
        auth: {
          xoauth2: {
            user: "XXXXXXXX@gmail.com",
            clientId: "XXXXXXX.apps.googleusercontent.com",
            clientSercret: "XXXXXXXXXX", <===
            refreshToken: "XXXXXXXX"
          }
```
Sorry for all this :tired_face:

**Comment by ggallo** [comment]
Alas I spoke to soon. Even after this is corrected, I get the same error stack.

**Comment by andris9** [comment]
See here for the details of using XOAuth2: https://github.com/andris9/nodemailer-smtp-transport#authentication
