### ISSUE TITLE
SSL23_GET_SERVER_HELLO:unknown protocol

### ISSUE THREAD

**Issue by mdumouchel** [andris9/smtp-connection#26]
Hello I'm having issues connecting to an IIS server that is using self signed cert (tls 1.2). 

My test file. 
```javascript
var SMTPConnection = require('smtp-connection');
var connection = new SMTPConnection({
	port: 25,
	host: 'hostName',
	ignoreTLS: true,
	debug: true,
	secure: true
});

connection.connect(function(err, success) {
	console.log(err, success);
});
```
My Error.
```javascript
Error: 139984928708416:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:782:

    at SlabBuffer.use (tls.js:235:18)
    at CleartextStream.read [as _read] (tls.js:455:29)
    at CleartextStream.Readable.read (_stream_readable.js:341:10)
    at EncryptedStream.write [as _write] (tls.js:369:25)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at EncryptedStream.Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at Socket.pipeOnReadable (_stream_readable.js:643:5)
```
Do you see anything wrong here?

**Comment by mdumouchel** [comment]
I am able to connect to the smtp server using 

````
openssl s_client -debug -starttls smtp -crlf -connect hostName:25
```

and send mail.

**Comment by andris9** [comment]
Set 'secure' to false. This server does not support initial encrypted commenctions, it srtarts out as plaintext and later upgrades to TLS using the starttls command

**Comment by keith24** [comment]
I'm getting this error too.  My configuration appears correct: 

```javascript
var transporter = nodemailer.createTransport({
  host: 'subdomain.domain.tld',
  port: 587,
  secure: true,
  auth: {
    user: 'email@domain.tld',
    pass: 'secret'
  }
});
```

However, attempting to send a message throws: 

```javascript
{ [Error: 140145798559520:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:794: code: 'ECONNECTION', command: 'CONN' }
```

Following your instructions, I set `secure` to `false`, but then get this error: 

```javascript
{ [Error: Invalid login: 535 Refused. Authentication failed.]
 code: 'EAUTH',
 response: '535 Refused. Authentication failed.',
 responseCode: 535,
 command: 'AUTH PLAIN' }
```

I get this same error if I try port 465, as in [this suggestion](http://stackoverflow.com/a/38465870/3006854).  My [host's documentation](https://wiki.uberspace.de/mail#tldr) (German) is pretty explicit about using port 587 anyway.  

That's the only documentation they have on the subject, but I can always ask tech support.  The thing is, the same credentials are working fine with Django 1.9, but [another node package](https://www.npmjs.com/package/sendmail) is also giving me this problem.  Maybe node just needs some extra configuration...   

Then there's [this suggestion](http://stackoverflow.com/a/33104614/3006854), to set the cipher explicitly in nodemailer like so: 

```javascript
var transporter = nodemailer.createTransport({
  ...
  tls: {ciphers: "SSLv3"}
});
```

...but that also throws `unknown protocol`.  

Do you have any suggestions?  Google has nothing else for me.

**Comment by andris9** [comment]
@keith24 could you try the following configuration and tell me what the output is (it should log the entire SMTP transaction to console):

```
var transporter = nodemailer.createTransport({
  host: 'subdomain.domain.tld',
  port: 587,
  secure: false,
  auth: {
    user: 'email@domain.tld',
    pass: 'secret'
  },
  authMethod: 'LOGIN',
  logger: true,
  debug: true
});
```

**Comment by keith24** [comment]
Gladly: 

```sh
[2016-08-19 11:48:35] INFO: [x4Dzjrgoqfc] Connection established to 192.0.2.0:587
[2016-08-19 11:48:35] DEBUG: [x4Dzjrgoqfc] S: 220 subdomain.domain.tld ESMTP
[2016-08-19 11:48:35] DEBUG: [x4Dzjrgoqfc] C: EHLO subdomain.domain.tld
[2016-08-19 11:48:35] DEBUG: [x4Dzjrgoqfc] S: 250-STARTTLS
250-PIPELINING
250-8BITMIME
250 AUTH LOGIN PLAIN
[2016-08-19 11:48:35] DEBUG: [x4Dzjrgoqfc] C: STARTTLS
[2016-08-19 11:48:35] DEBUG: [x4Dzjrgoqfc] S: 220 Proceed.
[2016-08-19 11:48:36] INFO: [x4Dzjrgoqfc] Connection upgraded with STARTTLS
[2016-08-19 11:48:36] DEBUG: [x4Dzjrgoqfc] C: EHLO subdomain.domain.de
[2016-08-19 11:48:36] DEBUG: [x4Dzjrgoqfc] S: 250 AUTH LOGIN PLAIN
[2016-08-19 11:48:36] DEBUG: [x4Dzjrgoqfc] SMTP handshake finished
[2016-08-19 11:48:36] DEBUG: [x4Dzjrgoqfc] C: AUTH LOGIN
[2016-08-19 11:48:36] DEBUG: [x4Dzjrgoqfc] S: 334 VXNlcm5hbWU6
[2016-08-19 11:48:36] DEBUG: [x4Dzjrgoqfc] C: bWFpbEBrZWl0aGlyd2luLnVz
[2016-08-19 11:48:36] DEBUG: [x4Dzjrgoqfc] S: 334 UGFzc3dvcmQ6
[2016-08-19 11:48:36] DEBUG: [x4Dzjrgoqfc] C: R3l0MjIzcXch
[2016-08-19 11:48:37] DEBUG: [x4Dzjrgoqfc] S: 535 Refused. Authentication failed.
[2016-08-19 11:48:37] INFO: [x4Dzjrgoqfc] User "email@domain.tld" failed to authenticate
[2016-08-19 11:48:37] DEBUG: [x4Dzjrgoqfc] Closing connection to the server using "end"
{ [Error: Invalid login: 535 Refused. Authentication failed.]
  code: 'EAUTH',
  response: '535 Refused. Authentication failed.',
  responseCode: 535,
  command: 'AUTH LOGIN' } undefined
{ [Error: Invalid login: 535 Refused. Authentication failed.]
   code: 'EAUTH',
  response: '535 Refused. Authentication failed.',
  responseCode: 535,
  command: 'AUTH LOGIN' }
[2016-08-19 11:48:37] INFO: [x4Dzjrgoqfc] Connection closed
```

**Comment by andris9** [comment]
Sorry, I forgot to mention that the log would include your username and password in base64. I edited these out but just in case you might want to change your password.

From the log it seems that everything works as it should and assuming your login credentials are valid, you should be able to log in. The error message seems to be from Spamdyke and maybe it is doing some kind of heuristical blocking? If I could see the SMTP transaction log for some other client that is able to log in using the same credentials then I could see where's the difference but right now I have no idea. Anyhow, from my point of view, everything works as intended.

What you can also try, is to use `authMethod: 'PLAIN'` to change the authentication method. Then you could also try to change the client hostname to something else with the `name` argument. Currently it seems to be using the same hostname as the server and maybe it triggers something in Spamdyke?

```
var transporter = nodemailer.createTransport({
  name: 'localhost',
  host: 'subdomain.domain.tld',
```

**Comment by keith24** [comment]
Ah, whoops.  OK, password changed.  

Using localhost threw some errors about not being in the DNS records.  'PLAIN' gave me the same issue.  I'll ask tech support about Spamdyke.  Thanks for your help!

**Comment by keith24** [comment]
Tech support basically said "lolwat".  

But it's working now!  I found [the solution](https://github.com/nodemailer/nodemailer/issues/358#issuecomment-67009829) in #358: 

> I had the same problem and solved it by setting `secure=false` _and **`requireTLS=true`**_. 
> -- meaku

**Comment by andris9** [comment]
@keith24  That's quite strange because in your case requireTLS affects nothing. As it can be seen from the logs you are already using STARTTLS. The option is there to force using it if the server for whatever reason does not advertise support for it. Could you provide a new log (with the credentials removed) to see what's now different?

**Comment by keith24** [comment]
Sure.  By the way, I just noticed I've been posting in `nodemailer/smtp-connection`.  The code is probably the same, but in this example I'm using `nodemailer/nodemailer`.  

Here's the working config: 

```javascript
var transporter = nodemailer.createTransport({
	host: 'sub.domain.tld',
	port: 587,
	secure: false,
	requireTLS: true,
	auth: {
		user: 'usename@sub.domain.tld',
		pass: 'Supersecretpassword'
	},
  logger: true,
  debug: true
});
transporter.verify(function(err, success) {
	if (err){ console.log('SMTP Error:\n',err); }
	console.log(success?'SMTP ready...':'SMTP not ready!');
});
```

Logs while making and verifying connection: 

```sh
[2016-08-20 07:36:56] INFO: [QsdXWgJJn8] Connection established to xxx.xxx.xxx.xxx:587
[2016-08-20 07:36:56] DEBUG: [QsdXWgJJn8] S: 220 sub.domain.tld ESMTP
[2016-08-20 07:36:56] DEBUG: [QsdXWgJJn8] C: EHLO sub.domain.tld
[2016-08-20 07:36:56] DEBUG: [QsdXWgJJn8] S: 250-STARTTLS
250-PIPELINING
250-8BITMIME
250 AUTH LOGIN PLAIN
[2016-08-20 07:36:56] DEBUG: [QsdXWgJJn8] C: STARTTLS
[2016-08-20 07:36:56] DEBUG: [QsdXWgJJn8] S: 220 Proceed.
[2016-08-20 07:36:57] INFO: [QsdXWgJJn8] Connection upgraded with STARTTLS
[2016-08-20 07:36:57] DEBUG: [QsdXWgJJn8] C: EHLO sub.domain.tld
[2016-08-20 07:36:57] DEBUG: [QsdXWgJJn8] S: 250 AUTH LOGIN PLAIN
[2016-08-20 07:36:57] DEBUG: [QsdXWgJJn8] SMTP handshake finished
[2016-08-20 07:36:57] DEBUG: [QsdXWgJJn8] C: AUTH PLAIN [ redacted ]
[2016-08-20 07:36:57] DEBUG: [QsdXWgJJn8] S: 235 Proceed.
[2016-08-20 07:36:57] INFO: [QsdXWgJJn8] User "username@sub.domain.tld" authenticated
[2016-08-20 07:36:57] DEBUG: [QsdXWgJJn8] C: QUIT
SMTP ready... 
DEBUG: [QsdXWgJJn8] S: 221 sub.domain.tld
DEBUG: [QsdXWgJJn8] Closing connection to the server using "end"
INFO: [QsdXWgJJn8] Connection closed
```

Logs while sending a message: 

```sh
INFO: Sending mail using SMTP/2.6.0[client:2.8.0]
INFO: [RXcS5Z9u0a8] Connection established to xxx.xxx.xxx.xxx:587
DEBUG: [RXcS5Z9u0a8] S: 220 sub.domain.tld ESMTP
[2016-08-20 07:41:12] DEBUG: [RXcS5Z9u0a8] C: EHLO sub.domain.tld
[2016-08-20 07:41:12] DEBUG: [RXcS5Z9u0a8] S: 250-STARTTLS
250-PIPELINING
250-8BITMIME
250 AUTH LOGIN PLAIN
[2016-08-20 07:41:12] DEBUG: [RXcS5Z9u0a8] C: STARTTLS
[2016-08-20 07:41:12] DEBUG: [RXcS5Z9u0a8] S: 220 Proceed.
[2016-08-20 07:41:13] INFO: [RXcS5Z9u0a8] Connection upgraded with STARTTLS
[2016-08-20 07:41:13] DEBUG: [RXcS5Z9u0a8] C: EHLO sub.domain.tld
[2016-08-20 07:41:13] DEBUG: [RXcS5Z9u0a8] S: 250 AUTH LOGIN PLAIN
[2016-08-20 07:41:13] DEBUG: [RXcS5Z9u0a8] SMTP handshake finished
[2016-08-20 07:41:13] DEBUG: [RXcS5Z9u0a8] C: AUTH PLAIN [ redacted ]
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] S: 235 Proceed.
[2016-08-20 07:41:14] INFO: [RXcS5Z9u0a8] User "username@sub.domain.tld" authenticated
[2016-08-20 07:41:14] INFO: Sending message <d38c9f60-239f-639c-d453-************@keithirwin.us> to <toaddress@keithirwin.us>
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] C: MAIL FROM:<fromaddress@keithirwin.us>
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] S: 250 ok
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] C: RCPT TO:<toaddress@keithirwin.us>
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] S: 250 ok
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] C: DATA
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] S: 354 go ahead
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] C: Content-Type: text/plain
From: From Name <fromaddress@keithirwin.us>
To: To Name <toaddress@keithirwin.us>
Subject: The subject
Message-ID: <d38c9f60-239f-639c-d453-************@keithirwin.us>
X-Mailer: nodemailer (2.5.0; +http://nodemailer.com/;
 SMTP/2.6.0[client:2.8.0])
Content-Transfer-Encoding: 7bit
Date: Sat, 20 Aug 2016 07:41:12 +0000
MIME-Version: 1.0

[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] C: test
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] C: 
.
[2016-08-20 07:41:14] INFO: [RXcS5Z9u0a8] C: <405 bytes encoded mime message (source size 400 bytes)>
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] S: 250 ok 1471678874 qp 32729
[2016-08-20 07:41:14] DEBUG: [RXcS5Z9u0a8] Closing connection to the server using "end"
[2016-08-20 07:41:14] INFO: [RXcS5Z9u0a8] Connection closed
```

**Comment by nikhil-sahu** [comment]
I faced the same problem and using `secure:false` worked alright for me
